
package PizzaEnLinea.modelo.pizza;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicioPizza", targetNamespace = "http://servicios/", wsdlLocation = "http://localhost:8084/pizzasEnLinea_WS_/ServicioPizza?wsdl")
public class ServicioPizza_Service
    extends Service
{

    private final static URL SERVICIOPIZZA_WSDL_LOCATION;
    private final static WebServiceException SERVICIOPIZZA_EXCEPTION;
    private final static QName SERVICIOPIZZA_QNAME = new QName("http://servicios/", "ServicioPizza");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8084/pizzasEnLinea_WS_/ServicioPizza?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOPIZZA_WSDL_LOCATION = url;
        SERVICIOPIZZA_EXCEPTION = e;
    }

    public ServicioPizza_Service() {
        super(__getWsdlLocation(), SERVICIOPIZZA_QNAME);
    }

    public ServicioPizza_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOPIZZA_QNAME, features);
    }

    public ServicioPizza_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOPIZZA_QNAME);
    }

    public ServicioPizza_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOPIZZA_QNAME, features);
    }

    public ServicioPizza_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioPizza_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioPizza
     */
    @WebEndpoint(name = "ServicioPizzaPort")
    public ServicioPizza getServicioPizzaPort() {
        return super.getPort(new QName("http://servicios/", "ServicioPizzaPort"), ServicioPizza.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioPizza
     */
    @WebEndpoint(name = "ServicioPizzaPort")
    public ServicioPizza getServicioPizzaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicios/", "ServicioPizzaPort"), ServicioPizza.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOPIZZA_EXCEPTION!= null) {
            throw SERVICIOPIZZA_EXCEPTION;
        }
        return SERVICIOPIZZA_WSDL_LOCATION;
    }

}
