
package PizzaEnLinea.modelo.orden;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicioOrden", targetNamespace = "http://servicios/", wsdlLocation = "http://localhost:8084/pizzasEnLinea_WS_/ServicioOrden?wsdl")
public class ServicioOrden_Service
    extends Service
{

    private final static URL SERVICIOORDEN_WSDL_LOCATION;
    private final static WebServiceException SERVICIOORDEN_EXCEPTION;
    private final static QName SERVICIOORDEN_QNAME = new QName("http://servicios/", "ServicioOrden");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8084/pizzasEnLinea_WS_/ServicioOrden?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOORDEN_WSDL_LOCATION = url;
        SERVICIOORDEN_EXCEPTION = e;
    }

    public ServicioOrden_Service() {
        super(__getWsdlLocation(), SERVICIOORDEN_QNAME);
    }

    public ServicioOrden_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOORDEN_QNAME, features);
    }

    public ServicioOrden_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOORDEN_QNAME);
    }

    public ServicioOrden_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOORDEN_QNAME, features);
    }

    public ServicioOrden_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioOrden_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioOrden
     */
    @WebEndpoint(name = "ServicioOrdenPort")
    public ServicioOrden getServicioOrdenPort() {
        return super.getPort(new QName("http://servicios/", "ServicioOrdenPort"), ServicioOrden.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioOrden
     */
    @WebEndpoint(name = "ServicioOrdenPort")
    public ServicioOrden getServicioOrdenPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicios/", "ServicioOrdenPort"), ServicioOrden.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOORDEN_EXCEPTION!= null) {
            throw SERVICIOORDEN_EXCEPTION;
        }
        return SERVICIOORDEN_WSDL_LOCATION;
    }

}
