
package PizzaEnLinea.modelo.complemento;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicioComplemento", targetNamespace = "http://servicios/", wsdlLocation = "http://localhost:8084/pizzasEnLinea_WS_/ServicioComplemento?wsdl")
public class ServicioComplemento_Service
    extends Service
{

    private final static URL SERVICIOCOMPLEMENTO_WSDL_LOCATION;
    private final static WebServiceException SERVICIOCOMPLEMENTO_EXCEPTION;
    private final static QName SERVICIOCOMPLEMENTO_QNAME = new QName("http://servicios/", "ServicioComplemento");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8084/pizzasEnLinea_WS_/ServicioComplemento?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOCOMPLEMENTO_WSDL_LOCATION = url;
        SERVICIOCOMPLEMENTO_EXCEPTION = e;
    }

    public ServicioComplemento_Service() {
        super(__getWsdlLocation(), SERVICIOCOMPLEMENTO_QNAME);
    }

    public ServicioComplemento_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOCOMPLEMENTO_QNAME, features);
    }

    public ServicioComplemento_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOCOMPLEMENTO_QNAME);
    }

    public ServicioComplemento_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOCOMPLEMENTO_QNAME, features);
    }

    public ServicioComplemento_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioComplemento_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioComplemento
     */
    @WebEndpoint(name = "ServicioComplementoPort")
    public ServicioComplemento getServicioComplementoPort() {
        return super.getPort(new QName("http://servicios/", "ServicioComplementoPort"), ServicioComplemento.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioComplemento
     */
    @WebEndpoint(name = "ServicioComplementoPort")
    public ServicioComplemento getServicioComplementoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicios/", "ServicioComplementoPort"), ServicioComplemento.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOCOMPLEMENTO_EXCEPTION!= null) {
            throw SERVICIOCOMPLEMENTO_EXCEPTION;
        }
        return SERVICIOCOMPLEMENTO_WSDL_LOCATION;
    }

}
