
package PizzaEnLinea.modelo.ingrediente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicioIngredientes", targetNamespace = "http://servicios/", wsdlLocation = "http://localhost:8084/pizzasEnLinea_WS_/ServicioIngredientes?wsdl")
public class ServicioIngredientes_Service
    extends Service
{

    private final static URL SERVICIOINGREDIENTES_WSDL_LOCATION;
    private final static WebServiceException SERVICIOINGREDIENTES_EXCEPTION;
    private final static QName SERVICIOINGREDIENTES_QNAME = new QName("http://servicios/", "ServicioIngredientes");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8084/pizzasEnLinea_WS_/ServicioIngredientes?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOINGREDIENTES_WSDL_LOCATION = url;
        SERVICIOINGREDIENTES_EXCEPTION = e;
    }

    public ServicioIngredientes_Service() {
        super(__getWsdlLocation(), SERVICIOINGREDIENTES_QNAME);
    }

    public ServicioIngredientes_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOINGREDIENTES_QNAME, features);
    }

    public ServicioIngredientes_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOINGREDIENTES_QNAME);
    }

    public ServicioIngredientes_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOINGREDIENTES_QNAME, features);
    }

    public ServicioIngredientes_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioIngredientes_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioIngredientes
     */
    @WebEndpoint(name = "ServicioIngredientesPort")
    public ServicioIngredientes getServicioIngredientesPort() {
        return super.getPort(new QName("http://servicios/", "ServicioIngredientesPort"), ServicioIngredientes.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioIngredientes
     */
    @WebEndpoint(name = "ServicioIngredientesPort")
    public ServicioIngredientes getServicioIngredientesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicios/", "ServicioIngredientesPort"), ServicioIngredientes.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOINGREDIENTES_EXCEPTION!= null) {
            throw SERVICIOINGREDIENTES_EXCEPTION;
        }
        return SERVICIOINGREDIENTES_WSDL_LOCATION;
    }

}
