
package PizzaEnLinea.modelo.ingrediente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioIngredientes", targetNamespace = "http://servicios/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioIngredientes {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarIngredientes", targetNamespace = "http://servicios/", className = "PizzaEnLinea.modelo.ingrediente.ListarIngredientes")
    @ResponseWrapper(localName = "listarIngredientesResponse", targetNamespace = "http://servicios/", className = "PizzaEnLinea.modelo.ingrediente.ListarIngredientesResponse")
    @Action(input = "http://servicios/ServicioIngredientes/listarIngredientesRequest", output = "http://servicios/ServicioIngredientes/listarIngredientesResponse")
    public String listarIngredientes();

    /**
     * 
     * @param nombre
     * @param value
     * @param campo
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateIngrediente", targetNamespace = "http://servicios/", className = "PizzaEnLinea.modelo.ingrediente.UpdateIngrediente")
    @ResponseWrapper(localName = "updateIngredienteResponse", targetNamespace = "http://servicios/", className = "PizzaEnLinea.modelo.ingrediente.UpdateIngredienteResponse")
    @Action(input = "http://servicios/ServicioIngredientes/updateIngredienteRequest", output = "http://servicios/ServicioIngredientes/updateIngredienteResponse")
    public String updateIngrediente(
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "campo", targetNamespace = "")
        String campo,
        @WebParam(name = "value", targetNamespace = "")
        String value);

    /**
     * 
     * @param nombre
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteIngrediente", targetNamespace = "http://servicios/", className = "PizzaEnLinea.modelo.ingrediente.DeleteIngrediente")
    @ResponseWrapper(localName = "deleteIngredienteResponse", targetNamespace = "http://servicios/", className = "PizzaEnLinea.modelo.ingrediente.DeleteIngredienteResponse")
    @Action(input = "http://servicios/ServicioIngredientes/deleteIngredienteRequest", output = "http://servicios/ServicioIngredientes/deleteIngredienteResponse")
    public String deleteIngrediente(
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre);

    /**
     * 
     * @param precio
     * @param nombre
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertIngredientes", targetNamespace = "http://servicios/", className = "PizzaEnLinea.modelo.ingrediente.InsertIngredientes")
    @ResponseWrapper(localName = "insertIngredientesResponse", targetNamespace = "http://servicios/", className = "PizzaEnLinea.modelo.ingrediente.InsertIngredientesResponse")
    @Action(input = "http://servicios/ServicioIngredientes/insertIngredientesRequest", output = "http://servicios/ServicioIngredientes/insertIngredientesResponse")
    public String insertIngredientes(
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "precio", targetNamespace = "")
        String precio);

    /**
     * 
     * @param nombre
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarIngrediente", targetNamespace = "http://servicios/", className = "PizzaEnLinea.modelo.ingrediente.BuscarIngrediente")
    @ResponseWrapper(localName = "buscarIngredienteResponse", targetNamespace = "http://servicios/", className = "PizzaEnLinea.modelo.ingrediente.BuscarIngredienteResponse")
    @Action(input = "http://servicios/ServicioIngredientes/buscarIngredienteRequest", output = "http://servicios/ServicioIngredientes/buscarIngredienteResponse")
    public String buscarIngrediente(
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre);

}
